export const EVENT_COLORS = {
    login: "#0ea5e9",
    login_success: "#0ea5e9",
    logout: "#0ea5e9",
    site_created: "#10b981",
    site_updated: "#3b82f6",
    site_deleted: "#ef4444",
    device_updated: "#3b82f6",
    device_created: "#10b981",
    device_deleted: "#d78f72",
    customer_updated: "#3b82f6",
    customer_created: "#10b981",
    customer_deleted: "#ef4444",
    video_update: "#3b82f6",
    video_created: "#10b981",
    video_deleted: "#ef4444",
    device_offline: "#ef4444",
    default: "#64748b",
};

export const EVENT_LABELS = {
    login: "Sessão iniciada",
    login_success: "Sessão iniciada",
    logout: "Sessão terminada",
    site_created: "Local criado",
    site_updated: "Local atualizado",
    site_deleted: "Local removido",
    device_created: "Dispositivo criado",
    device_updated: "Dispositivo atualizado",
    video_created: "Vídeo adicionado",
    video_update: "Vídeo atualizado",
    video_deleted: "Vídeo removido",
    customer_created: "Cliente criado",
    customer_updated: "Cliente atualizado",
    customer_deleted: "Cliente removido",
    device_offline: "TV offline",
    default: "Outro evento",
};